// CodexBWAI — real native MSI generation/extraction, never product installation.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, copyFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const windows = process.platform === 'win32';
test('native MSI carries every payload byte and refuses output overwrite', { skip: !windows }, async () => {
  const work = await mkdtemp(path.join(tmpdir(), 'blastcast-msi-test-'));
  const payload = path.join(work, 'payload');
  await mkdir(path.join(payload, 'resources', 'folder with spaces'), { recursive: true });
  await copyFile(path.join(process.env.SystemRoot, 'System32', 'whoami.exe'), path.join(payload, 'BlastCast.exe'));
  await writeFile(path.join(payload, 'resources', 'folder with spaces', 'example.json'), '{"preserve":true}\n');
  await writeFile(path.join(payload, 'blastcast-inventory.json'), JSON.stringify({ target: 'win32-x64', appVersion: '0.1.0' }));
  const output = path.join(work, 'fixture.msi');
  const powershell = path.join(process.env.SystemRoot, 'System32', 'WindowsPowerShell', 'v1.0', 'powershell.exe');
  const run = (script, args) => spawnSync(powershell, ['-NoProfile', '-NonInteractive', '-ExecutionPolicy', 'RemoteSigned', '-File', path.join(root, 'packaging', 'windows', script), ...args], { encoding: 'utf8', timeout: 120_000 });
  const build = run('installer.ps1', ['-Payload', payload, '-Output', output, '-Version', '0.1.0']);
  assert.equal(build.status, 0, build.stderr + build.stdout);
  const preflight = run('preflight-installer.ps1', ['-Msi', output]);
  assert.equal(preflight.status, 0, preflight.stderr + preflight.stdout);
  const preflightReport = JSON.parse((await readFile(output + '.preflight.json', 'utf8')).replace(/^\uFEFF/, ''));
  assert.equal(preflightReport.windowsMajor, '#10');
  assert.equal(preflightReport.welcomePreviewCreated, true, preflightReport.welcomePreviewError);
  assert.equal(preflightReport.actions.AppSearch, 1);
  assert.equal(preflightReport.actions.LaunchConditions, 1);
  assert.equal(preflightReport.installationPerformed, false);
  const before = await readFile(output);
  const rejected = run('installer.ps1', ['-Payload', payload, '-Output', output, '-Version', '0.1.0']);
  assert.notEqual(rejected.status, 0);
  assert.deepEqual(await readFile(output), before);
  const inspect = run('inspect-installer.ps1', ['-Msi', output, '-Payload', payload, '-Extract', path.join(work, 'admin-image')]);
  assert.equal(inspect.status, 0, inspect.stderr + inspect.stdout);
  const report = JSON.parse((await readFile(output + '.inspection.json', 'utf8')).replace(/^\uFEFF/, ''));
  assert.equal(report.extractedFilesHashVerified, 3);
  assert.equal(report.installPerformed, false);
});
